name: garadi
favicon: null
layout_spectrum: 0.49595
typography_spectrum: 0.51847
title: Garadi Entertainments
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b7c1ca'
    - '#13140f'
    - '#676e66'
    - '#bfab0e'
    - '#c92d42'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
