name: garadi
favicon: null
layout_spectrum: 0.28342
typography_spectrum: 0.51847
title: Garadi Entertainments
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010006'
    - '#ea0212'
    - '#ffffff'
    - '#40384f'
    - '#bba099'
  brandStrength: 0.5253293355926871
  lightness: 0.5285192131996155
  saturation: 0.336261689895764
  rhythmicContrast: 0.8759677701164037
purpose: []
